name: Build Sphinx Documentation

on:
  pull_request:
    branches: [ master ]

jobs:
  sphinx-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: ammaraskar/sphinx-action@master
        with:
          # git is required to clone the docs theme
          # before custom requirement are resolved https://github.com/ammaraskar/sphinx-action/issues/16
          pre-build-command: "apt-get update -y && apt-get install -y git && pip install -r docs/requirements.txt && pip install ."  
          docs-folder: "docs/"
      - name: Test Documentation
        env:
          SPHINX_MOCK_REQUIREMENTS: 0
        run: |
          # First run the same pipeline as Read-The-Docs
          sudo apt-get update && sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          apt-get update && apt-get install -y cmake
          cd docs
          make clean
          make html
        shell: bash
